### ISSUE TITLE
ეს კომანდი აქ რატომ არის?

### ISSUE THREAD

**Issue by MariamKipshidze** [Gvantsie/Library_Management_System#7]
https://github.com/Gvantsie/Library_Management_System/blob/4e096b8a9333740e635f3d2328699bd7ffa402cf/library/tests/test_import_books.py#L1

**Comment by Gvantsie** [comment]
ვაი :))
კომანდის სატესტო კოდის წერას ვცდილობდი მაგრამ რაღაც არ გამომივიდა ბოლომდე და ისევ მაგ ფაილში გამიგრძელებია კომანდის წერა. გავასწორებ ახლავე <3 რაც იმპორტ ბუქსში წერია არ ეშვებოდა და როგორ დააგენერირეთ წიგნები?
